# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_hello_twice', 'positive_affirmation']

# Cell
def say_hello(subject:str):
    """Say hello to `subject`."""
    return f"Hello {subject}!"

# Cell
def say_hello_twice(subject):
    """Says hello twice using `say_hello`."""
    return say_hello(subject) + " " + say_hello(subject)

# Cell
def positive_affirmation():
    """Say some words of encouragement."""
    return "You can do it!!!"