# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(subject):
    """Say hello to `subject`."""
    return f"Hello {subject}!"